services:
  hadoop-master:
    build: .
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"
      - "9864:9864"
      - "8088:8088"
      - "9000:9000"
      - "50070:50070"
      - "50075:50075"
    volumes:
      - hadoop-master-data:/usr/local/hadoop/hdfs
    networks:
      - hadoop

  hadoop-slave1:
    build: .
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    depends_on:
      - hadoop-master
    volumes:
      - hadoop-slave1-data:/usr/local/hadoop/hdfs
    networks:
      - hadoop

  hadoop-slave2:
    build: .
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    depends_on:
      - hadoop-master
    volumes:
      - hadoop-slave2-data:/usr/local/hadoop/hdfs
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge

volumes:
  hadoop-master-data:
  hadoop-slave1-data:
  hadoop-slave2-data:
